### ISSUE TITLE
Feature Request for a scroll bar

### ISSUE THREAD

**Issue by CSab6482** [iandwelker/smserver#91]
WebMessage has this implemented for both the chat list and the selected conversation, and I find it very useful. Would it be possible to implement?

**Comment by iandwelker** [comment]
It would be easy to implement, however I'm (personally) not a fan of it; the scroll bars of most browsers aren't especially pretty and somewhat take away from the iMessage feel (in my opinion). However, you can easily implement the scrollbar for just your own host by adding a custom CSS file to your host device with the following content:
```css
* {
    scrollbar-width: auto !important
}
::-webkit-scrollbar {
    display: inherit !important;
}
```
